services:
  espie:
    container_name: espie
    build:
      context: .
    ports:
      - "8000:3000"
      - "8003:3000"
    volumes:
      - ./data:/app/data
      - ./plugins:/app/plugins
    environment:
      - TZ=UTC
      - NODE_OPTIONS=--max-old-space-size=512
      - DATABASE_PATH=/app/data/db/espie.db
      - BIN_DIR=/app/data/bin
      - TZ_OFFSET_HOURS=0
      - YTMUSIC_DIR=/app/data/ytmusic
      - HA_BASE_URL=${HA_BASE_URL:-}
      - HA_TOKEN=${HA_TOKEN:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    restart: unless-stopped
